name: update

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: update
      run: bash build/update.sh
    # Deploy the site
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
        force_orphan: true
